apiVersion: apps/v1
kind: Deployment
metadata:
  name: mom
  labels:
    app: mom
spec:
  selector:
    matchLabels:
      app: mom
  replicas: 1
  template:
    metadata:
      labels:
        app: mom
    spec:
      containers:
        - name: mom
          image: champkub6/service1:v5.0.0
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3

      nodeSelector:
        node-role.kubernetes.io/worker: worker
---
apiVersion: v1
kind: Service
metadata:
  name: mom
spec:
  selector:
    app: mom
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
